"""auto update

Revision ID: 8046f4c8b646
Revises: 
Create Date: 2026-01-17 02:19:12.793685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8046f4c8b646'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fornitore_id', sa.Integer(), nullable=False),
    sa.Column('data_ordine', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_consegna', sa.DateTime(timezone=True), nullable=True),
    sa.Column('categoria_prodotto', sa.String(), nullable=False),
    sa.Column('quantita', sa.Float(), nullable=False),
    sa.Column('prezzo_totale', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquisti_id'), 'acquisti', ['id'], unique=False)
    op.create_table('fornitori',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornitori_id'), 'fornitori', ['id'], unique=False)
    op.create_table('vendite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canale_vendita', sa.String(), nullable=False),
    sa.Column('categoria_prodotto', sa.String(), nullable=False),
    sa.Column('quantita', sa.Float(), nullable=False),
    sa.Column('prezzo_totale', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendite_id'), 'vendite', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendite_id'), table_name='vendite')
    op.drop_table('vendite')
    op.drop_index(op.f('ix_fornitori_id'), table_name='fornitori')
    op.drop_table('fornitori')
    op.drop_index(op.f('ix_acquisti_id'), table_name='acquisti')
    op.drop_table('acquisti')
    # ### end Alembic commands ###